language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iceubb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iceubb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-116024886319'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
